name: Build & release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install dependencies
        run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build for Linux
        run: |
          cargo build --release
          cd target/release
          tar cvzf deep_abyss_linux_${{github.ref_name}}.tar.gz deep_abyss ../../assets

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files:
            target/release/deep_abyss_linux_${{github.ref_name}}.tar.gz

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build for windows
        run: |
          cargo build --release
          cd target/release
          7z a -tzip deep_abyss_windows_${{github.ref_name}}.zip deep_abyss.exe ../../assets

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:
            target/release/deep_abyss_windows_${{github.ref_name}}.zip
